export const DEMO_ITEMS = [
  {
    _id: "demo1",
    title: "Old NCERT Physics Book",
    price: 350,
    description: "Slightly used, excellent condition for 1st semester B.Tech. A must-have basic text for all CSE students.",
    location: "Hostel A, Room 301",
    category: "Books & Stationery",
    courseSemester: "B.Tech CSE - 1 Sem",
    images: ["https://studentadvisorbooks.in/wp-content/uploads/2023/12/Physics-class-12-TB.png"],
    student: { email: "seller1@university.edu", name: "Ravi Sharma" },
  },
  {
    _id: "demo2",
    title: "Dell Latitude Laptop (i5/8GB)",
    price: 18000,
    description: "i5 processor, 8GB RAM, 256GB SSD. Perfect for programming and light gaming. Recently serviced.",
    location: "Hostel C, Room 112",
    category: "Laptops",
    courseSemester: "B.Tech CSE - 4 Sem",
    images: ["https://cdn11.bigcommerce.com/s-w5trgcbv/images/stencil/1920w/products/7918/62488/Dell_Latitude_7480_Right__52111.1645138602.jpg?c=2"],
    student: { email: "seller2@university.edu", name: "Priya Singh" },
  },
  {
    _id: "demo3",
    title: "Casio Scientific Calculator",
    price: 500,
    description: "FX-991ES PLUS model. Required for engineering calculations. Comes with original cover.",
    location: "Day Scholar's Block",
    category: "Electronics",
    courseSemester: "B.Tech CSE - 2 Sem",
    images: ["https://images-eu.ssl-images-amazon.com/images/I/61U8vBXM44L.jpg"],
    student: { email: "seller3@university.edu", name: "Amit Verma" },
  },
];